apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiGateway.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.apiGateway.name }}
  ports:
    - port: {{ .Values.apiGateway.port }}
      targetPort: {{ .Values.apiGateway.port }}
      protocol: TCP
