const express = require('express');
const router = express.Router();
const { protect } = require('../../middlewares/authMiddleware');
const ctrl = require('./controller');
router.use(protect);
router.get('/dashboard', ctrl.getEcommerceDashboard);
router.route('/products').get(ctrl.getProducts).post(ctrl.createProduct);
router.get('/products/search', ctrl.searchProducts);
router.route('/products/:id').get(ctrl.getProduct).put(ctrl.updateProduct).delete(ctrl.deleteProduct);
router.route('/orders').get(ctrl.getOrders).post(ctrl.createOrder);
router.route('/orders/:id').get(ctrl.getOrder);
router.put('/orders/:id/status', ctrl.updateOrderStatus);
router.put('/orders/:id/cancel', ctrl.cancelOrder);
router.get('/cart/:customerId', ctrl.getCart);
router.post('/cart', ctrl.addToCart);
router.put('/cart/:id', ctrl.updateCart);
router.delete('/cart/:id', ctrl.clearCart);
router.delete('/cart/:id/items/:productId', ctrl.removeFromCart);
router.route('/categories').get(ctrl.getCategories).post(ctrl.createCategory);
router.put('/categories/:id', ctrl.updateCategory);
router.route('/vendors').get(ctrl.getVendors).post(ctrl.createVendor);
router.route('/vendors/:id').get(ctrl.getVendor).put(ctrl.updateVendor);
router.route('/reviews').get(ctrl.getReviews).post(ctrl.createReview);
router.put('/reviews/:id', ctrl.updateReview);
router.route('/coupons').get(ctrl.getCoupons).post(ctrl.createCoupon);
router.post('/coupons/validate', ctrl.validateCoupon);
router.route('/shipments').get(ctrl.getShipments);
router.put('/shipments/:id/status', ctrl.updateShipmentStatus);
module.exports = router;
