const express = require('express');
const router = express.Router();
const { protect } = require('../../middlewares/authMiddleware');
const ctrl = require('./controller');
router.use(protect);
router.get('/dashboard', ctrl.getHRDashboard);
router.route('/employees').get(ctrl.getEmployees).post(ctrl.createEmployee);
router.route('/employees/:id').get(ctrl.getEmployee).put(ctrl.updateEmployee);
router.put('/employees/:id/terminate', ctrl.terminateEmployee);
router.get('/employees/:id/analytics', ctrl.getEmployeeAnalytics);
router.route('/departments').get(ctrl.getDepartments).post(ctrl.createDepartment);
router.route('/departments/:id').get(ctrl.getDepartment).put(ctrl.updateDepartment);
router.route('/attendance').get(ctrl.getAttendance);
router.post('/attendance/checkin', ctrl.checkIn);
router.post('/attendance/checkout', ctrl.checkOut);
router.get('/attendance/summary/:empId', ctrl.getAttendanceSummary);
router.route('/leaves').get(ctrl.getLeaves).post(ctrl.requestLeave);
router.put('/leaves/:id/status', ctrl.updateLeaveStatus);
router.get('/leaves/balance/:empId', ctrl.getLeaveBalance);
router.route('/payrolls').get(ctrl.getPayrolls).post(ctrl.processPayroll);
router.get('/payrolls/:id/slip', ctrl.getPayslip);
router.put('/payrolls/:id/approve', ctrl.approvePayroll);
router.route('/performance').get(ctrl.getPerformanceReviews).post(ctrl.createReview);
router.put('/performance/:id', ctrl.updateReview);
router.get('/performance/summary/:empId', ctrl.getPerformanceSummary);
router.route('/jobs').get(ctrl.getJobPostings).post(ctrl.createJobPosting);
router.route('/jobs/:id').put(ctrl.updateJobPosting);
router.put('/jobs/:id/close', ctrl.closeJobPosting);
router.route('/trainings').get(ctrl.getTrainings).post(ctrl.createTraining);
router.put('/trainings/:id', ctrl.updateTraining);
router.post('/trainings/:id/enroll', ctrl.enrollEmployee);
module.exports = router;
