const express = require('express');
const router = express.Router();
const { protect } = require('../../middlewares/authMiddleware');
const ctrl = require('./controller');
router.use(protect);
router.get('/dashboard', ctrl.getCRMDashboard);
router.route('/contacts').get(ctrl.getContacts).post(ctrl.createContact);
router.post('/contacts/import', ctrl.importContacts);
router.route('/contacts/:id').get(ctrl.getContact).put(ctrl.updateContact).delete(ctrl.deleteContact);
router.route('/leads').get(ctrl.getLeads).post(ctrl.createLead);
router.route('/leads/:id').get(ctrl.getLead).put(ctrl.updateLead);
router.put('/leads/:id/convert', ctrl.convertLead);
router.get('/leads/:id/score', ctrl.scoreLead);
router.route('/deals').get(ctrl.getDeals).post(ctrl.createDeal);
router.get('/deals/by-stage', ctrl.getDealsByStage);
router.route('/deals/:id').get(ctrl.getDeal).put(ctrl.updateDeal).delete(ctrl.deleteDeal);
router.route('/activities').get(ctrl.getActivities).post(ctrl.createActivity);
router.route('/activities/:id').put(ctrl.updateActivity);
router.put('/activities/:id/complete', ctrl.completeActivity);
router.route('/pipelines').get(ctrl.getPipelines).post(ctrl.createPipeline);
router.put('/pipelines/:id', ctrl.updatePipeline);
router.route('/campaigns').get(ctrl.getCampaigns).post(ctrl.createCampaign);
router.route('/campaigns/:id').get(ctrl.getCampaign).put(ctrl.updateCampaign);
router.get('/campaigns/:id/analytics', ctrl.getCampaignAnalytics);
router.route('/tickets').get(ctrl.getTickets).post(ctrl.createTicket);
router.route('/tickets/:id').get(ctrl.getTicket).put(ctrl.updateTicket);
router.put('/tickets/:id/resolve', ctrl.resolveTicket);
module.exports = router;
